### ISSUE TITLE
Raise ActiveRecord::StatementInvalid: Mysql2::Error: Incorrect prefix key; when bin/rails db:reset is execute

### ISSUE THREAD

**Issue by ghost** [winebarrel/armg#8]
### Description

In case of existing spatial index, I execute ` bin/rails db:reset` and see raise error. 
Also, `bin/rails db:migrate` is success.

Below is schema.rb and stack trace.

schema.rb
```ruby
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `rails
# db:schema:load`. When creating a new database, `rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 2020_05_10_071430) do

  create_table "locations", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4", force: :cascade do |t|
    t.geometry "location", null: false
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["location"], name: "idx_location", length: 32, type: :spatial
  end
end
```

stack trace

```ruby
~/Desktop/app %bin/rails db:reset
Dropped database 'app_development'
Dropped database 'app_test'
Created database 'app_development'
Created database 'app_test'
/Users/UserName/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/armg-0.8.1/lib/armg/table_definition_ext.rb:6: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/UserName/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3/lib/active_record/connection_adapters/abstract/schema_definitions.rb:364: warning: The called method `column' is defined here
rails aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Incorrect prefix key; the used key part isn't a string, the used length is longer than the key part, or the storage engine doesn't support unique prefix keys
/Users/UserName/Desktop/app/db/schema.rb:15:in `block in <main>'
/Users/UserName/Desktop/app/db/schema.rb:13:in `<main>'
/Users/UserName/Desktop/app/bin/rails:9:in `<top (required)>'
/Users/UserName/Desktop/app/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
Mysql2::Error: Incorrect prefix key; the used key part isn't a string, the used length is longer than the key part, or the storage engine doesn't support unique prefix keys
/Users/UserName/Desktop/app/db/schema.rb:15:in `block in <main>'
/Users/UserName/Desktop/app/db/schema.rb:13:in `<main>'
/Users/UserName/Desktop/app/bin/rails:9:in `<top (required)>'
/Users/UserName/Desktop/app/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)
```

### Expected behavior

There is no error.

### Actual behavior

`Mysql2::Error` is occured.

### System configuration

**Rails version**: 6.0.3

**Ruby version**: 2.7.0p0

**armg version**: 0.8.1

**Comment by ghost** [comment]
I will close because it is inactive.
